name: Main

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Make 1GB file with 1MB block
        run: | 
          mkdir folder
          dd if=/dev/zero of=folder/1g1Mbs.img count=1024 bs=1M
          ls -lR
          du -h .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 1g1Mbs
          path: folder
      - name: Clean
        run: rm -rf *

      - name: Make 1GB file with 2MB block
        run: | 
          mkdir folder
          dd if=/dev/zero of=folder/1g2Mbs.img count=512 bs=2M
          ls -lR
          du -h .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 1g2Mbs
          path: folder
      - name: Clean
        run: rm -rf *
