name: Main

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get metadata
        run: |
          echo "==="
          df -Th .
          echo "==="
          stat -f .
          echo "==="
          cat /etc/fstab
          echo "==="
      - name: Make 10GB file with 1MB block
        run: | 
          mkdir folder
          dd if=/dev/urandom of=folder/1g1Mbs.img count=1M bs=1M
          echo "==="
          ls -lR
          echo "==="
          du -h .
          echo "==="
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 10G
          path: folder
      - name: Clean
        run: rm -rf *
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: 10G
      - name: Check file size
        run: | 
          echo "==="
          ls -lR
          echo "==="
          du -h .
          echo "==="